services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=easydemandasdb;Username=postgres;Password=0
    depends_on:
      - db

  #webfront:
   # build:
    #  context: ../easydemandasfront
    #  dockerfile: Dockerfile
   # ports:
    #  - "3000:80" # Maps local port 3000 to Nginx port 80
    #depends_on:
     # - webapi

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0
      - POSTGRES_DB=easydemandasdb
    ports:
      - "5432:5432" # Allows local dev tools like pgAdmin or DBeaver to connect
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
