using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace easydemandasapi.Migrations
{
    public partial class SeedDemoData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Helper: avança sequence de IDENTITY column para o maior Id existente
            // Usa ALTER TABLE que funciona com GENERATED BY DEFAULT AS IDENTITY (Npgsql)

            migrationBuilder.Sql(@"
                INSERT INTO ""Cargos"" (""Id"", ""Nome"") VALUES
                (1, 'Analista de Sistemas'),
                (2, 'Gerente'),
                (3, 'Técnico de Suporte'),
                (4, 'Analista Financeiro'),
                (5, 'Coordenador de Operações')
                ON CONFLICT (""Id"") DO NOTHING;
            ");
            migrationBuilder.Sql(@"
                DO $$ DECLARE n INT;
                BEGIN SELECT COALESCE(MAX(""Id""),0)+1 INTO n FROM ""Cargos"";
                EXECUTE 'ALTER TABLE ""Cargos"" ALTER COLUMN ""Id"" RESTART WITH '||n; END $$;
            ");

            migrationBuilder.Sql(@"
                INSERT INTO ""Empregados"" (""Id"",""Nome"",""Sobrenome"",""Email"",""Telefone"",""Endereco"",""Cpf"",""DataNascimento"",""CargoId"",""DataContratacao"",""DepartamentoId"") VALUES
                (1,  'Ana',      'Santos',    'ana.santos@empresa.com',        '11991001001','Rua das Flores, 100, SP',       '11122233300','1988-03-15',1,'2018-01-10',NULL),
                (2,  'Bruno',    'Oliveira',  'bruno.oliveira@empresa.com',    '11991002002','Av. Paulista, 200, SP',          '22233344411','1985-07-22',2,'2015-06-01',NULL),
                (3,  'Carla',    'Pereira',   'carla.pereira@empresa.com',     '11991003003','Rua XV, 300, Curitiba',         '33344455522','1990-11-05',4,'2019-03-20',NULL),
                (4,  'Daniel',   'Costa',     'daniel.costa@empresa.com',      '11991004004','Av. Brasil, 400, RJ',           '44455566633','1982-09-18',3,'2012-08-15',NULL),
                (5,  'Elena',    'Ferreira',  'elena.ferreira@empresa.com',    '11991005005','Rua do Comércio, 500, BH',      '55566677744','1993-04-30',5,'2020-01-05',NULL),
                (6,  'Felipe',   'Lima',      'felipe.lima@empresa.com',       '11991006006','Rua Sete, 600, Fortaleza',      '66677788855','1987-12-10',1,'2017-09-12',NULL),
                (7,  'Gabriela', 'Souza',     'gabriela.souza@empresa.com',    '11991007007','Av. Central, 700, POA',         '77788899966','1991-06-25',3,'2021-04-01',NULL),
                (8,  'Henrique', 'Rodrigues', 'henrique.rodrigues@empresa.com','11991008008','Rua Nova, 800, Salvador',       '88899900077','1984-02-14',4,'2014-11-20',NULL),
                (9,  'Isabela',  'Martins',   'isabela.martins@empresa.com',   '11991009009','Av. das Nações, 900, Brasília', '99900011188','1995-08-08',2,'2022-07-01',NULL),
                (10, 'João',     'Alves',     'joao.alves@empresa.com',        '11991010010','Rua Principal, 1000, Manaus',   '00011122299','1989-10-20',5,'2016-03-25',NULL)
                ON CONFLICT (""Id"") DO NOTHING;
            ");
            migrationBuilder.Sql(@"
                DO $$ DECLARE n INT;
                BEGIN SELECT COALESCE(MAX(""Id""),0)+1 INTO n FROM ""Empregados"";
                EXECUTE 'ALTER TABLE ""Empregados"" ALTER COLUMN ""Id"" RESTART WITH '||n; END $$;
            ");

            migrationBuilder.Sql(@"
                INSERT INTO ""Departamentos"" (""Id"",""Nome"",""Sigla"",""ResponsavelId"") VALUES
                (1,'Tecnologia da Informação','TI', 1),
                (2,'Recursos Humanos',        'RH', 2),
                (3,'Financeiro',              'FIN',3),
                (4,'Operações',               'OPS',4)
                ON CONFLICT (""Id"") DO NOTHING;
            ");
            migrationBuilder.Sql(@"
                DO $$ DECLARE n INT;
                BEGIN SELECT COALESCE(MAX(""Id""),0)+1 INTO n FROM ""Departamentos"";
                EXECUTE 'ALTER TABLE ""Departamentos"" ALTER COLUMN ""Id"" RESTART WITH '||n; END $$;
            ");

            migrationBuilder.Sql(@"
                UPDATE ""Empregados"" SET ""DepartamentoId""=1 WHERE ""Id"" IN (1,6,7) AND ""DepartamentoId"" IS NULL;
                UPDATE ""Empregados"" SET ""DepartamentoId""=2 WHERE ""Id"" IN (2,9)   AND ""DepartamentoId"" IS NULL;
                UPDATE ""Empregados"" SET ""DepartamentoId""=3 WHERE ""Id"" IN (3,8)   AND ""DepartamentoId"" IS NULL;
                UPDATE ""Empregados"" SET ""DepartamentoId""=4 WHERE ""Id"" IN (4,5,10) AND ""DepartamentoId"" IS NULL;
            ");

            migrationBuilder.Sql(@"
                INSERT INTO ""Chamados"" (""Id"",""Titulo"",""Descricao"",""Status"",""DataAbertura"",""SolicitanteId"") VALUES
                (1, 'Computador não liga',           'PC do escritório não está ligando.',          'Aberto',       '2026-03-10',6),
                (2, 'Acesso ao sistema bloqueado',   'Usuário sem acesso ao ERP.',                 'Aberto',       '2026-03-12',9),
                (3, 'Impressora offline',            'Impressora do financeiro sem resposta.',      'Aberto',       '2026-03-15',8),
                (4, 'Erro no relatório mensal',      'Relatório com valores incorretos.',           'Aberto',       '2026-03-18',3),
                (5, 'VPN não conecta',               'Colaborador remoto sem acesso à VPN.',       'Aberto',       '2026-03-20',6),
                (6, 'Backup não realizado',          'Rotina de backup falhou na sexta.',          'Aberto',       '2026-03-22',1),
                (7, 'Lentidão no sistema',           'Sistema lento após atualização.',             'Aberto',       '2026-04-01',10),
                (8, 'E-mail corporativo inacessível','Sem acesso ao e-mail há dois dias.',         'Aberto',       '2026-04-03',9),
                (9, 'Servidor de arquivos fora do ar','Servidor de arquivos offline.',             'Aberto',       '2026-04-05',6),
                (10,'Câmera de segurança sem sinal', 'Câmera do corredor perdeu sinal.',           'Aberto',       '2026-04-07',4),
                (11,'Instalação de software',        'Instalar Office em 5 computadores.',         'Em Andamento','2026-02-10',7),
                (12,'Migração de dados',             'Migrar dados do sistema legado.',            'Em Andamento','2026-02-12',1),
                (13,'Configuração de roteador',      'Novo roteador no andar 3.',                  'Em Andamento','2026-02-15',6),
                (14,'Treinamento de sistema',        'Capacitar RH no sistema de ponto.',          'Em Andamento','2026-02-20',2),
                (15,'Desenvolvimento de dashboard',  'Painel de métricas para diretoria.',         'Em Andamento','2026-02-25',1),
                (16,'Auditoria de acessos',          'Revisar permissões de todos os usuários.',   'Em Andamento','2026-03-01',3),
                (17,'Atualização de antivírus',      'Atualizar antivírus na rede.',               'Em Andamento','2026-03-03',7),
                (18,'Implantação de firewall',       'Configurar firewall corporativo.',            'Em Andamento','2026-03-05',1),
                (19,'Revisão de contratos TI',       'Revisar contratos de manutenção.',           'Em Andamento','2026-03-08',9),
                (20,'Problema de rede wi-fi',        'Sinal wi-fi instável no 2º andar.',          'Em Andamento','2026-03-09',5),
                (21,'Integração de sistemas',        'Integrar RH com folha de pagamento.',        'Em Andamento','2026-03-10',2),
                (22,'Upgrade de servidores',         'Aumentar RAM dos servidores.',               'Em Andamento','2026-03-11',1),
                (23,'Troca de monitor',              'Monitor do diretor com tela quebrada.',      'Concluído',   '2026-01-05',8),
                (24,'Reset de senha',                'Redefinir senha do colaborador.',            'Concluído',   '2026-01-08',10),
                (25,'Instalação de impressora',      'Nova impressora no RH.',                     'Concluído',   '2026-01-10',2),
                (26,'Criação de usuário',            'Usuário para o novo estagiário.',            'Concluído',   '2026-01-12',9),
                (27,'Backup recuperado',             'Recuperar backup do dia 05/01.',             'Concluído',   '2026-01-15',6),
                (28,'Atualização de Windows',        'Atualizar SO em 10 máquinas.',               'Concluído',   '2026-01-18',7),
                (29,'Configuração de e-mail',        'Conta de e-mail para nova colaboradora.',    'Concluído',   '2026-01-20',5),
                (30,'Substituição de HD',            'HD com falha no notebook da gerente.',       'Concluído',   '2026-01-22',3),
                (31,'Treinamento de segurança',      'Boas práticas de segurança para equipe.',    'Concluído',   '2026-02-01',1),
                (32,'Configuração de VPN',           'VPN para 3 colaboradores remotos.',          'Concluído',   '2026-02-03',6),
                (33,'Instalação de sistema CFTV',    'Câmeras no depósito.',                       'Concluído',   '2026-02-05',4),
                (34,'Limpeza de vírus',              'Vírus no computador do administrativo.',     'Concluído',   '2026-02-07',10),
                (35,'Suporte ao ERP',                'Bug crítico no módulo de faturamento.',      'Concluído',   '2026-02-09',8),
                (36,'Compra de notebooks',           'Compra de 20 notebooks cortada.',            'Cancelado',   '2026-01-28',9),
                (37,'Sistema de videoconferência',   'Implantação cancelada.',                     'Cancelado',   '2026-02-01',2),
                (38,'Troca de servidores',           'Projeto adiado para próximo fiscal.',        'Cancelado',   '2026-02-14',1),
                (39,'Migração para nuvem',           'Suspenso por decisão da diretoria.',         'Cancelado',   '2026-03-01',6),
                (40,'App mobile corporativo',        'Cancelado após reavaliação de escopo.',      'Cancelado',   '2026-03-15',1)
                ON CONFLICT (""Id"") DO NOTHING;
            ");
            migrationBuilder.Sql(@"
                DO $$ DECLARE n INT;
                BEGIN SELECT COALESCE(MAX(""Id""),0)+1 INTO n FROM ""Chamados"";
                EXECUTE 'ALTER TABLE ""Chamados"" ALTER COLUMN ""Id"" RESTART WITH '||n; END $$;
            ");

            migrationBuilder.Sql(@"
                INSERT INTO ""DetalhesChamados"" (""Id"",""ChamadoId"",""DepartamentoId"",""Custo"",""NivelCriticidade"",""Observacoes"",""Encaminhamentos"") VALUES
                (1, 1, 1, 850.00,  'Alto',   'PC não respondeu ao botão de força.',       'Encaminhado para troca de fonte.'),
                (2, 2, 2, 0.00,    'Medio',  'Bloqueio inesperado após troca de senha.',   'Aguardando confirmação.'),
                (3, 3, 3, 450.00,  'Baixo',  'Impressora sem resposta no ping.',           'Verificar cabo de rede.'),
                (4, 4, 3, 0.00,    'Alto',   'Relatório errado há dois meses.',            'Solicitar auditoria de dados.'),
                (5, 5, 1, 0.00,    'Alto',   'Usuário em home office sem acesso.',        'Aguardando suporte VPN.'),
                (6, 6, 1, 200.00,  'Critico','Backup sem rodar há 5 dias.',               'Verificar agendador de tarefas.'),
                (7, 7, 1, 0.00,    'Medio',  'Lentidão após patch de segurança.',         'Investigando logs.'),
                (8, 8, 2, 0.00,    'Alto',   'Problema no servidor Exchange.',             NULL),
                (9, 9, 1, 1200.00, 'Critico','Servidor down — sem acesso a arquivos.',    'TI acionada com urgência.'),
                (10,10, 4, 3500.00,'Alto',   'Câmera sem imagem.',                        'Técnico CFTV convocado.'),
                (11,11, 1, 2800.00,'Baixo',  'Licenças adquiridas.',                      'Agendado para próxima semana.'),
                (12,12, 1,15000.00,'Alto',   'Migração 60% concluída.',                   'Equipe dedicada.'),
                (13,13, 1, 600.00, 'Medio',  'Roteador em configuração.',                 'Previsto para quinta.'),
                (14,14, 2, 1200.00,'Baixo',  'Primeira turma treinada.',                  NULL),
                (15,15, 1,28000.00,'Medio',  'Levantamento realizado.',                   'Desenvolvimento iniciado.'),
                (16,16, 2, 500.00, 'Alto',   '30% dos usuários revisados.',               'Prazo: 15 dias.'),
                (17,17, 1, 0.00,   'Baixo',  '40 máquinas atualizadas de 120.',           NULL),
                (18,18, 1,45000.00,'Critico','Firewall instalado, config em revisão.',    'Consultoria externa.'),
                (19,19, 3, 800.00, 'Baixo',  '5 contratos revisados de 18.',              NULL),
                (20,20, 1, 0.00,   'Medio',  'Problema no AP do 2º andar.',               'Aguardando peça.'),
                (21,21, 2,22000.00,'Alto',   'Integração 70% concluída.',                 'Prazo: próximo mês.'),
                (22,22, 1,38000.00,'Alto',   'Hardware em trânsito.',                     'Chegada em 10 dias.'),
                (23,23, 3, 1800.00,'Baixo',  'Monitor substituído.',                      'Resolvido em 1 dia.'),
                (24,24, 2, 0.00,   'Baixo',  'Senha redefinida.',                         'Resolvido em 30min.'),
                (25,25, 2, 750.00, 'Baixo',  'Impressora instalada e testada.',           'Resolvido em 2 dias.'),
                (26,26, 2, 0.00,   'Baixo',  'Usuário criado com permissões básicas.',    'Resolvido no dia.'),
                (27,27, 1, 400.00, 'Critico','Banco restaurado com 99,9% dos dados.',     '6h de dados perdidas.'),
                (28,28, 1, 0.00,   'Baixo',  'Atualizações sem intercorrências.',         'Feito no fim de semana.'),
                (29,29, 2, 0.00,   'Baixo',  'E-mail configurado e testado.',             'Resolvido em 1h.'),
                (30,30, 2, 1200.00,'Alto',   'HD substituído e dados recuperados.',       'Backup restabelecido.'),
                (31,31, 1, 3500.00,'Medio',  'Treinamento para 45 colaboradores.',        'Aprovação: 92%.'),
                (32,32, 1, 0.00,   'Medio',  'VPN testada pelos 3 colaboradores.',        'Resolvido em 2 dias.'),
                (33,33, 4,18000.00,'Medio',  '8 câmeras instaladas no depósito.',         'Integrado ao CFTV.'),
                (34,34, 1, 200.00, 'Alto',   'Vírus removido e HD verificado.',           'Máquina formatada.'),
                (35,35, 3, 9500.00,'Critico','Bug corrigido em produção.',                'Hotfix aplicado.'),
                (36,36, 2, NULL,   'Baixo',  'Pedido negado pelo financeiro.',            'Cortado no orçamento.'),
                (37,37, 1, NULL,   'Baixo',  'Contrato não assinado.',                   'Projeto suspenso.'),
                (38,38, 1, NULL,   'Alto',   'Orçamento aprovado mas projeto adiado.',   'Revisão no próximo ano.'),
                (39,39, 1, NULL,   'Alto',   'Estudo de viabilidade concluído.',          'Revisão estratégica.'),
                (40,40, 1, NULL,   'Medio',  'Escopo amplo demais para o prazo.',         'Reabrir em projetos menores.')
                ON CONFLICT (""Id"") DO NOTHING;
            ");
            migrationBuilder.Sql(@"
                DO $$ DECLARE n INT;
                BEGIN SELECT COALESCE(MAX(""Id""),0)+1 INTO n FROM ""DetalhesChamados"";
                EXECUTE 'ALTER TABLE ""DetalhesChamados"" ALTER COLUMN ""Id"" RESTART WITH '||n; END $$;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DELETE FROM ""DetalhesChamados"" WHERE ""Id"" BETWEEN 1 AND 40;
                DELETE FROM ""Chamados""          WHERE ""Id"" BETWEEN 1 AND 40;
                UPDATE ""Empregados"" SET ""DepartamentoId""=NULL WHERE ""Id"" BETWEEN 1 AND 10;
                DELETE FROM ""Departamentos""     WHERE ""Id"" BETWEEN 1 AND 4;
                DELETE FROM ""Empregados""        WHERE ""Id"" BETWEEN 1 AND 10;
                DELETE FROM ""Cargos""            WHERE ""Id"" BETWEEN 1 AND 5;
            ");
        }
    }
}
