// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using easydemandasapi.Data;

#nullable disable

namespace easydemandasapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624145742_AddAtivoToChamado")]
    partial class AddAtivoToChamado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("easydemandasapi.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cargos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Diretor"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Gerente"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Analista"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Técnico"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Assistente"
                        },
                        new
                        {
                            Id = 9999,
                            Nome = "CARGO INDETERMINADO"
                        });
                });

            modelBuilder.Entity("easydemandasapi.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Chamados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 1 aberto para resolução de erro no erp #1. Favor analisar com atenção.",
                            SolicitanteId = 1,
                            Status = "Aberto",
                            Titulo = "Erro no ERP #1"
                        },
                        new
                        {
                            Id = 2,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 2 aberto para resolução de reset de senha #2. Favor analisar com atenção.",
                            SolicitanteId = 2,
                            Status = "Em Andamento",
                            Titulo = "Reset de Senha #2"
                        },
                        new
                        {
                            Id = 3,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 3 aberto para resolução de problema com vpn #3. Favor analisar com atenção.",
                            SolicitanteId = 3,
                            Status = "Concluído",
                            Titulo = "Problema com VPN #3"
                        },
                        new
                        {
                            Id = 4,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 4 aberto para resolução de impressora não funciona #4. Favor analisar com atenção.",
                            SolicitanteId = 4,
                            Status = "Cancelado",
                            Titulo = "Impressora Não Funciona #4"
                        },
                        new
                        {
                            Id = 5,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 5 aberto para resolução de lentidão na estação #5. Favor analisar com atenção.",
                            SolicitanteId = 5,
                            Status = "Aberto",
                            Titulo = "Lentidão na Estação #5"
                        },
                        new
                        {
                            Id = 6,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 6 aberto para resolução de falha de conectividade #6. Favor analisar com atenção.",
                            SolicitanteId = 6,
                            Status = "Em Andamento",
                            Titulo = "Falha de Conectividade #6"
                        },
                        new
                        {
                            Id = 7,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 7 aberto para resolução de instalação de office #7. Favor analisar com atenção.",
                            SolicitanteId = 7,
                            Status = "Concluído",
                            Titulo = "Instalação de Office #7"
                        },
                        new
                        {
                            Id = 8,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 8 aberto para resolução de acesso ao servidor #8. Favor analisar com atenção.",
                            SolicitanteId = 8,
                            Status = "Cancelado",
                            Titulo = "Acesso ao Servidor #8"
                        },
                        new
                        {
                            Id = 9,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 9 aberto para resolução de ajuste de permissões #9. Favor analisar com atenção.",
                            SolicitanteId = 9,
                            Status = "Aberto",
                            Titulo = "Ajuste de Permissões #9"
                        },
                        new
                        {
                            Id = 10,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 10 aberto para resolução de solicitação de upgrade #10. Favor analisar com atenção.",
                            SolicitanteId = 10,
                            Status = "Em Andamento",
                            Titulo = "Solicitação de Upgrade #10"
                        },
                        new
                        {
                            Id = 11,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 11 aberto para resolução de erro no erp #11. Favor analisar com atenção.",
                            SolicitanteId = 11,
                            Status = "Concluído",
                            Titulo = "Erro no ERP #11"
                        },
                        new
                        {
                            Id = 12,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 12 aberto para resolução de reset de senha #12. Favor analisar com atenção.",
                            SolicitanteId = 12,
                            Status = "Cancelado",
                            Titulo = "Reset de Senha #12"
                        },
                        new
                        {
                            Id = 13,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 13 aberto para resolução de problema com vpn #13. Favor analisar com atenção.",
                            SolicitanteId = 13,
                            Status = "Aberto",
                            Titulo = "Problema com VPN #13"
                        },
                        new
                        {
                            Id = 14,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 14 aberto para resolução de impressora não funciona #14. Favor analisar com atenção.",
                            SolicitanteId = 14,
                            Status = "Em Andamento",
                            Titulo = "Impressora Não Funciona #14"
                        },
                        new
                        {
                            Id = 15,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 15 aberto para resolução de lentidão na estação #15. Favor analisar com atenção.",
                            SolicitanteId = 15,
                            Status = "Concluído",
                            Titulo = "Lentidão na Estação #15"
                        },
                        new
                        {
                            Id = 16,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 16 aberto para resolução de falha de conectividade #16. Favor analisar com atenção.",
                            SolicitanteId = 16,
                            Status = "Cancelado",
                            Titulo = "Falha de Conectividade #16"
                        },
                        new
                        {
                            Id = 17,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 17 aberto para resolução de instalação de office #17. Favor analisar com atenção.",
                            SolicitanteId = 17,
                            Status = "Aberto",
                            Titulo = "Instalação de Office #17"
                        },
                        new
                        {
                            Id = 18,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 18 aberto para resolução de acesso ao servidor #18. Favor analisar com atenção.",
                            SolicitanteId = 18,
                            Status = "Em Andamento",
                            Titulo = "Acesso ao Servidor #18"
                        },
                        new
                        {
                            Id = 19,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 19 aberto para resolução de ajuste de permissões #19. Favor analisar com atenção.",
                            SolicitanteId = 19,
                            Status = "Concluído",
                            Titulo = "Ajuste de Permissões #19"
                        },
                        new
                        {
                            Id = 20,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 20 aberto para resolução de solicitação de upgrade #20. Favor analisar com atenção.",
                            SolicitanteId = 20,
                            Status = "Cancelado",
                            Titulo = "Solicitação de Upgrade #20"
                        },
                        new
                        {
                            Id = 21,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 21 aberto para resolução de erro no erp #21. Favor analisar com atenção.",
                            SolicitanteId = 21,
                            Status = "Aberto",
                            Titulo = "Erro no ERP #21"
                        },
                        new
                        {
                            Id = 22,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 22 aberto para resolução de reset de senha #22. Favor analisar com atenção.",
                            SolicitanteId = 22,
                            Status = "Em Andamento",
                            Titulo = "Reset de Senha #22"
                        },
                        new
                        {
                            Id = 23,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 23 aberto para resolução de problema com vpn #23. Favor analisar com atenção.",
                            SolicitanteId = 23,
                            Status = "Concluído",
                            Titulo = "Problema com VPN #23"
                        },
                        new
                        {
                            Id = 24,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 24 aberto para resolução de impressora não funciona #24. Favor analisar com atenção.",
                            SolicitanteId = 24,
                            Status = "Cancelado",
                            Titulo = "Impressora Não Funciona #24"
                        },
                        new
                        {
                            Id = 25,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 25 aberto para resolução de lentidão na estação #25. Favor analisar com atenção.",
                            SolicitanteId = 25,
                            Status = "Aberto",
                            Titulo = "Lentidão na Estação #25"
                        },
                        new
                        {
                            Id = 26,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 26 aberto para resolução de falha de conectividade #26. Favor analisar com atenção.",
                            SolicitanteId = 26,
                            Status = "Em Andamento",
                            Titulo = "Falha de Conectividade #26"
                        },
                        new
                        {
                            Id = 27,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 27 aberto para resolução de instalação de office #27. Favor analisar com atenção.",
                            SolicitanteId = 27,
                            Status = "Concluído",
                            Titulo = "Instalação de Office #27"
                        },
                        new
                        {
                            Id = 28,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 28 aberto para resolução de acesso ao servidor #28. Favor analisar com atenção.",
                            SolicitanteId = 28,
                            Status = "Cancelado",
                            Titulo = "Acesso ao Servidor #28"
                        },
                        new
                        {
                            Id = 29,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 29 aberto para resolução de ajuste de permissões #29. Favor analisar com atenção.",
                            SolicitanteId = 29,
                            Status = "Aberto",
                            Titulo = "Ajuste de Permissões #29"
                        },
                        new
                        {
                            Id = 30,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 30 aberto para resolução de solicitação de upgrade #30. Favor analisar com atenção.",
                            SolicitanteId = 30,
                            Status = "Em Andamento",
                            Titulo = "Solicitação de Upgrade #30"
                        },
                        new
                        {
                            Id = 31,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 31 aberto para resolução de erro no erp #31. Favor analisar com atenção.",
                            SolicitanteId = 1,
                            Status = "Concluído",
                            Titulo = "Erro no ERP #31"
                        },
                        new
                        {
                            Id = 32,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 32 aberto para resolução de reset de senha #32. Favor analisar com atenção.",
                            SolicitanteId = 2,
                            Status = "Cancelado",
                            Titulo = "Reset de Senha #32"
                        },
                        new
                        {
                            Id = 33,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 33 aberto para resolução de problema com vpn #33. Favor analisar com atenção.",
                            SolicitanteId = 3,
                            Status = "Aberto",
                            Titulo = "Problema com VPN #33"
                        },
                        new
                        {
                            Id = 34,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 34 aberto para resolução de impressora não funciona #34. Favor analisar com atenção.",
                            SolicitanteId = 4,
                            Status = "Em Andamento",
                            Titulo = "Impressora Não Funciona #34"
                        },
                        new
                        {
                            Id = 35,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 35 aberto para resolução de lentidão na estação #35. Favor analisar com atenção.",
                            SolicitanteId = 5,
                            Status = "Concluído",
                            Titulo = "Lentidão na Estação #35"
                        },
                        new
                        {
                            Id = 36,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 36 aberto para resolução de falha de conectividade #36. Favor analisar com atenção.",
                            SolicitanteId = 6,
                            Status = "Cancelado",
                            Titulo = "Falha de Conectividade #36"
                        },
                        new
                        {
                            Id = 37,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 37 aberto para resolução de instalação de office #37. Favor analisar com atenção.",
                            SolicitanteId = 7,
                            Status = "Aberto",
                            Titulo = "Instalação de Office #37"
                        },
                        new
                        {
                            Id = 38,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 38 aberto para resolução de acesso ao servidor #38. Favor analisar com atenção.",
                            SolicitanteId = 8,
                            Status = "Em Andamento",
                            Titulo = "Acesso ao Servidor #38"
                        },
                        new
                        {
                            Id = 39,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 39 aberto para resolução de ajuste de permissões #39. Favor analisar com atenção.",
                            SolicitanteId = 9,
                            Status = "Concluído",
                            Titulo = "Ajuste de Permissões #39"
                        },
                        new
                        {
                            Id = 40,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 40 aberto para resolução de solicitação de upgrade #40. Favor analisar com atenção.",
                            SolicitanteId = 10,
                            Status = "Cancelado",
                            Titulo = "Solicitação de Upgrade #40"
                        },
                        new
                        {
                            Id = 41,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 41 aberto para resolução de erro no erp #41. Favor analisar com atenção.",
                            SolicitanteId = 11,
                            Status = "Aberto",
                            Titulo = "Erro no ERP #41"
                        },
                        new
                        {
                            Id = 42,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 42 aberto para resolução de reset de senha #42. Favor analisar com atenção.",
                            SolicitanteId = 12,
                            Status = "Em Andamento",
                            Titulo = "Reset de Senha #42"
                        },
                        new
                        {
                            Id = 43,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 43 aberto para resolução de problema com vpn #43. Favor analisar com atenção.",
                            SolicitanteId = 13,
                            Status = "Concluído",
                            Titulo = "Problema com VPN #43"
                        },
                        new
                        {
                            Id = 44,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 44 aberto para resolução de impressora não funciona #44. Favor analisar com atenção.",
                            SolicitanteId = 14,
                            Status = "Cancelado",
                            Titulo = "Impressora Não Funciona #44"
                        },
                        new
                        {
                            Id = 45,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 45 aberto para resolução de lentidão na estação #45. Favor analisar com atenção.",
                            SolicitanteId = 15,
                            Status = "Aberto",
                            Titulo = "Lentidão na Estação #45"
                        },
                        new
                        {
                            Id = 46,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 46 aberto para resolução de falha de conectividade #46. Favor analisar com atenção.",
                            SolicitanteId = 16,
                            Status = "Em Andamento",
                            Titulo = "Falha de Conectividade #46"
                        },
                        new
                        {
                            Id = 47,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 2, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 47 aberto para resolução de instalação de office #47. Favor analisar com atenção.",
                            SolicitanteId = 17,
                            Status = "Concluído",
                            Titulo = "Instalação de Office #47"
                        },
                        new
                        {
                            Id = 48,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 48 aberto para resolução de acesso ao servidor #48. Favor analisar com atenção.",
                            SolicitanteId = 18,
                            Status = "Cancelado",
                            Titulo = "Acesso ao Servidor #48"
                        },
                        new
                        {
                            Id = 49,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 49 aberto para resolução de ajuste de permissões #49. Favor analisar com atenção.",
                            SolicitanteId = 19,
                            Status = "Aberto",
                            Titulo = "Ajuste de Permissões #49"
                        },
                        new
                        {
                            Id = 50,
                            Ativo = true,
                            DataAbertura = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Chamado número 50 aberto para resolução de solicitação de upgrade #50. Favor analisar com atenção.",
                            SolicitanteId = 20,
                            Status = "Em Andamento",
                            Titulo = "Solicitação de Upgrade #50"
                        });
                });

            modelBuilder.Entity("easydemandasapi.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("Sigla")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            Nome = "DEPARTAMENTO INDETERMINADO",
                            ResponsavelId = 9999,
                            Sigla = "IND"
                        },
                        new
                        {
                            Id = 1,
                            Nome = "Tecnologia da Informação",
                            ResponsavelId = 1,
                            Sigla = "TI"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Recursos Humanos",
                            ResponsavelId = 2,
                            Sigla = "RH"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Financeiro",
                            ResponsavelId = 3,
                            Sigla = "FIN"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Vendas",
                            ResponsavelId = 4,
                            Sigla = "VEN"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Marketing",
                            ResponsavelId = 5,
                            Sigla = "MKT"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Operações",
                            ResponsavelId = 6,
                            Sigla = "OPE"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Jurídico",
                            ResponsavelId = 7,
                            Sigla = "JUR"
                        });
                });

            modelBuilder.Entity("easydemandasapi.Models.DetalhesChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Custo")
                        .HasColumnType("numeric");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Encaminhamentos")
                        .HasColumnType("text");

                    b.Property<string>("NivelCriticidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.ToTable("DetalhesChamados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChamadoId = 1,
                            Custo = 75.50m,
                            DepartamentoId = 1,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 1.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 1 anexadas no histórico."
                        },
                        new
                        {
                            Id = 2,
                            ChamadoId = 2,
                            Custo = 151.00m,
                            DepartamentoId = 2,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 2.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 2 anexadas no histórico."
                        },
                        new
                        {
                            Id = 3,
                            ChamadoId = 3,
                            Custo = 226.50m,
                            DepartamentoId = 3,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 3.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 3 anexadas no histórico."
                        },
                        new
                        {
                            Id = 4,
                            ChamadoId = 4,
                            Custo = 302.00m,
                            DepartamentoId = 4,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 4.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 4 anexadas no histórico."
                        },
                        new
                        {
                            Id = 5,
                            ChamadoId = 5,
                            Custo = 377.50m,
                            DepartamentoId = 5,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 5.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 5 anexadas no histórico."
                        },
                        new
                        {
                            Id = 6,
                            ChamadoId = 6,
                            Custo = 453.00m,
                            DepartamentoId = 6,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 6.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 6 anexadas no histórico."
                        },
                        new
                        {
                            Id = 7,
                            ChamadoId = 7,
                            DepartamentoId = 7,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 7.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 7 anexadas no histórico."
                        },
                        new
                        {
                            Id = 8,
                            ChamadoId = 8,
                            Custo = 604.00m,
                            DepartamentoId = 1,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 8.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 8 anexadas no histórico."
                        },
                        new
                        {
                            Id = 9,
                            ChamadoId = 9,
                            Custo = 679.50m,
                            DepartamentoId = 2,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 9.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 9 anexadas no histórico."
                        },
                        new
                        {
                            Id = 10,
                            ChamadoId = 10,
                            Custo = 755.00m,
                            DepartamentoId = 3,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 10.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 10 anexadas no histórico."
                        },
                        new
                        {
                            Id = 11,
                            ChamadoId = 11,
                            Custo = 830.50m,
                            DepartamentoId = 4,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 11.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 11 anexadas no histórico."
                        },
                        new
                        {
                            Id = 12,
                            ChamadoId = 12,
                            Custo = 906.00m,
                            DepartamentoId = 5,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 12.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 12 anexadas no histórico."
                        },
                        new
                        {
                            Id = 13,
                            ChamadoId = 13,
                            Custo = 981.50m,
                            DepartamentoId = 6,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 13.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 13 anexadas no histórico."
                        },
                        new
                        {
                            Id = 14,
                            ChamadoId = 14,
                            DepartamentoId = 7,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 14.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 14 anexadas no histórico."
                        },
                        new
                        {
                            Id = 15,
                            ChamadoId = 15,
                            Custo = 1132.50m,
                            DepartamentoId = 1,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 15.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 15 anexadas no histórico."
                        },
                        new
                        {
                            Id = 16,
                            ChamadoId = 16,
                            Custo = 1208.00m,
                            DepartamentoId = 2,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 16.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 16 anexadas no histórico."
                        },
                        new
                        {
                            Id = 17,
                            ChamadoId = 17,
                            Custo = 1283.50m,
                            DepartamentoId = 3,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 17.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 17 anexadas no histórico."
                        },
                        new
                        {
                            Id = 18,
                            ChamadoId = 18,
                            Custo = 1359.00m,
                            DepartamentoId = 4,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 18.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 18 anexadas no histórico."
                        },
                        new
                        {
                            Id = 19,
                            ChamadoId = 19,
                            Custo = 1434.50m,
                            DepartamentoId = 5,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 19.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 19 anexadas no histórico."
                        },
                        new
                        {
                            Id = 20,
                            ChamadoId = 20,
                            Custo = 1510.00m,
                            DepartamentoId = 6,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 20.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 20 anexadas no histórico."
                        },
                        new
                        {
                            Id = 21,
                            ChamadoId = 21,
                            DepartamentoId = 7,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 21.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 21 anexadas no histórico."
                        },
                        new
                        {
                            Id = 22,
                            ChamadoId = 22,
                            Custo = 1661.00m,
                            DepartamentoId = 1,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 22.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 22 anexadas no histórico."
                        },
                        new
                        {
                            Id = 23,
                            ChamadoId = 23,
                            Custo = 1736.50m,
                            DepartamentoId = 2,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 23.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 23 anexadas no histórico."
                        },
                        new
                        {
                            Id = 24,
                            ChamadoId = 24,
                            Custo = 1812.00m,
                            DepartamentoId = 3,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 24.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 24 anexadas no histórico."
                        },
                        new
                        {
                            Id = 25,
                            ChamadoId = 25,
                            Custo = 1887.50m,
                            DepartamentoId = 4,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 25.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 25 anexadas no histórico."
                        },
                        new
                        {
                            Id = 26,
                            ChamadoId = 26,
                            Custo = 1963.00m,
                            DepartamentoId = 5,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 26.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 26 anexadas no histórico."
                        },
                        new
                        {
                            Id = 27,
                            ChamadoId = 27,
                            Custo = 2038.50m,
                            DepartamentoId = 6,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 27.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 27 anexadas no histórico."
                        },
                        new
                        {
                            Id = 28,
                            ChamadoId = 28,
                            DepartamentoId = 7,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 28.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 28 anexadas no histórico."
                        },
                        new
                        {
                            Id = 29,
                            ChamadoId = 29,
                            Custo = 2189.50m,
                            DepartamentoId = 1,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 29.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 29 anexadas no histórico."
                        },
                        new
                        {
                            Id = 30,
                            ChamadoId = 30,
                            Custo = 2265.00m,
                            DepartamentoId = 2,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 30.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 30 anexadas no histórico."
                        },
                        new
                        {
                            Id = 31,
                            ChamadoId = 31,
                            Custo = 2340.50m,
                            DepartamentoId = 3,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 31.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 31 anexadas no histórico."
                        },
                        new
                        {
                            Id = 32,
                            ChamadoId = 32,
                            Custo = 2416.00m,
                            DepartamentoId = 4,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 32.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 32 anexadas no histórico."
                        },
                        new
                        {
                            Id = 33,
                            ChamadoId = 33,
                            Custo = 2491.50m,
                            DepartamentoId = 5,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 33.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 33 anexadas no histórico."
                        },
                        new
                        {
                            Id = 34,
                            ChamadoId = 34,
                            Custo = 2567.00m,
                            DepartamentoId = 6,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 34.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 34 anexadas no histórico."
                        },
                        new
                        {
                            Id = 35,
                            ChamadoId = 35,
                            DepartamentoId = 7,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 35.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 35 anexadas no histórico."
                        },
                        new
                        {
                            Id = 36,
                            ChamadoId = 36,
                            Custo = 2718.00m,
                            DepartamentoId = 1,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 36.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 36 anexadas no histórico."
                        },
                        new
                        {
                            Id = 37,
                            ChamadoId = 37,
                            Custo = 2793.50m,
                            DepartamentoId = 2,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 37.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 37 anexadas no histórico."
                        },
                        new
                        {
                            Id = 38,
                            ChamadoId = 38,
                            Custo = 2869.00m,
                            DepartamentoId = 3,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 38.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 38 anexadas no histórico."
                        },
                        new
                        {
                            Id = 39,
                            ChamadoId = 39,
                            Custo = 2944.50m,
                            DepartamentoId = 4,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 39.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 39 anexadas no histórico."
                        },
                        new
                        {
                            Id = 40,
                            ChamadoId = 40,
                            Custo = 3020.00m,
                            DepartamentoId = 5,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 40.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 40 anexadas no histórico."
                        },
                        new
                        {
                            Id = 41,
                            ChamadoId = 41,
                            Custo = 3095.50m,
                            DepartamentoId = 6,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 41.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 41 anexadas no histórico."
                        },
                        new
                        {
                            Id = 42,
                            ChamadoId = 42,
                            DepartamentoId = 7,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 42.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 42 anexadas no histórico."
                        },
                        new
                        {
                            Id = 43,
                            ChamadoId = 43,
                            Custo = 3246.50m,
                            DepartamentoId = 1,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 43.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 43 anexadas no histórico."
                        },
                        new
                        {
                            Id = 44,
                            ChamadoId = 44,
                            Custo = 3322.00m,
                            DepartamentoId = 2,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 44.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 44 anexadas no histórico."
                        },
                        new
                        {
                            Id = 45,
                            ChamadoId = 45,
                            Custo = 3397.50m,
                            DepartamentoId = 3,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 45.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 45 anexadas no histórico."
                        },
                        new
                        {
                            Id = 46,
                            ChamadoId = 46,
                            Custo = 3473.00m,
                            DepartamentoId = 4,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 46.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 46 anexadas no histórico."
                        },
                        new
                        {
                            Id = 47,
                            ChamadoId = 47,
                            Custo = 3548.50m,
                            DepartamentoId = 5,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 47.",
                            NivelCriticidade = "Alto",
                            Observacoes = "Observações do ticket 47 anexadas no histórico."
                        },
                        new
                        {
                            Id = 48,
                            ChamadoId = 48,
                            Custo = 3624.00m,
                            DepartamentoId = 6,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 48.",
                            NivelCriticidade = "Critico",
                            Observacoes = "Observações do ticket 48 anexadas no histórico."
                        },
                        new
                        {
                            Id = 49,
                            ChamadoId = 49,
                            DepartamentoId = 7,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 49.",
                            NivelCriticidade = "Baixo",
                            Observacoes = "Observações do ticket 49 anexadas no histórico."
                        },
                        new
                        {
                            Id = 50,
                            ChamadoId = 50,
                            Custo = 3775.00m,
                            DepartamentoId = 1,
                            Encaminhamentos = "Direcionamento e encaminhamentos para chamado 50.",
                            NivelCriticidade = "Medio",
                            Observacoes = "Observações do ticket 50 anexadas no histórico."
                        });
                });

            modelBuilder.Entity("easydemandasapi.Models.Empregado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataContratacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoCaminho")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Empregados");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            CargoId = 9999,
                            Cpf = "00000000000",
                            DataContratacao = new DateOnly(1900, 1, 1),
                            DataNascimento = new DateOnly(1900, 1, 1),
                            Email = "indeterminado@easydemandas.com",
                            Endereco = "Indeterminado",
                            Nome = "EMPREGADO",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "INDETERMINADO",
                            Telefone = "00000000000"
                        },
                        new
                        {
                            Id = 1,
                            CargoId = 1,
                            Cpf = "00000000001",
                            DataContratacao = new DateOnly(2016, 2, 2),
                            DataNascimento = new DateOnly(1981, 2, 2),
                            Email = "ana.santos@easydemandas.com",
                            Endereco = "Rua das Flores, 101",
                            Nome = "Ana",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Santos",
                            Telefone = "11900000001"
                        },
                        new
                        {
                            Id = 2,
                            CargoId = 2,
                            Cpf = "00000000002",
                            DataContratacao = new DateOnly(2017, 3, 3),
                            DataNascimento = new DateOnly(1982, 3, 3),
                            Email = "bruno.oliveira@easydemandas.com",
                            Endereco = "Rua das Flores, 102",
                            Nome = "Bruno",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Oliveira",
                            Telefone = "11900000002"
                        },
                        new
                        {
                            Id = 3,
                            CargoId = 3,
                            Cpf = "00000000003",
                            DataContratacao = new DateOnly(2018, 4, 4),
                            DataNascimento = new DateOnly(1983, 4, 4),
                            Email = "carla.pereira@easydemandas.com",
                            Endereco = "Rua das Flores, 103",
                            Nome = "Carla",
                            Perfil = "Suporte",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Pereira",
                            Telefone = "11900000003"
                        },
                        new
                        {
                            Id = 4,
                            CargoId = 4,
                            Cpf = "00000000004",
                            DataContratacao = new DateOnly(2019, 5, 5),
                            DataNascimento = new DateOnly(1984, 5, 5),
                            Email = "daniel.costa@easydemandas.com",
                            Endereco = "Rua das Flores, 104",
                            Nome = "Daniel",
                            Perfil = "Usuario",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Costa",
                            Telefone = "11900000004"
                        },
                        new
                        {
                            Id = 5,
                            CargoId = 5,
                            Cpf = "00000000005",
                            DataContratacao = new DateOnly(2020, 6, 6),
                            DataNascimento = new DateOnly(1985, 6, 6),
                            Email = "elena.ferreira@easydemandas.com",
                            Endereco = "Rua das Flores, 105",
                            Nome = "Elena",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Ferreira",
                            Telefone = "11900000005"
                        },
                        new
                        {
                            Id = 6,
                            CargoId = 1,
                            Cpf = "00000000006",
                            DataContratacao = new DateOnly(2021, 7, 7),
                            DataNascimento = new DateOnly(1986, 7, 7),
                            Email = "felipe.lima@easydemandas.com",
                            Endereco = "Rua das Flores, 106",
                            Nome = "Felipe",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Lima",
                            Telefone = "11900000006"
                        },
                        new
                        {
                            Id = 7,
                            CargoId = 2,
                            Cpf = "00000000007",
                            DataContratacao = new DateOnly(2022, 8, 8),
                            DataNascimento = new DateOnly(1987, 8, 8),
                            Email = "gabriela.souza@easydemandas.com",
                            Endereco = "Rua das Flores, 107",
                            Nome = "Gabriela",
                            Perfil = "Suporte",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Souza",
                            Telefone = "11900000007"
                        },
                        new
                        {
                            Id = 8,
                            CargoId = 3,
                            Cpf = "00000000008",
                            DataContratacao = new DateOnly(2023, 9, 9),
                            DataNascimento = new DateOnly(1988, 9, 9),
                            DepartamentoId = 1,
                            Email = "henrique.rodrigues@easydemandas.com",
                            Endereco = "Rua das Flores, 108",
                            Nome = "Henrique",
                            Perfil = "Usuario",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Rodrigues",
                            Telefone = "11900000008"
                        },
                        new
                        {
                            Id = 9,
                            CargoId = 4,
                            Cpf = "00000000009",
                            DataContratacao = new DateOnly(2024, 10, 10),
                            DataNascimento = new DateOnly(1989, 10, 10),
                            DepartamentoId = 2,
                            Email = "isabela.martins@easydemandas.com",
                            Endereco = "Rua das Flores, 109",
                            Nome = "Isabela",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Martins",
                            Telefone = "11900000009"
                        },
                        new
                        {
                            Id = 10,
                            CargoId = 5,
                            Cpf = "00000000010",
                            DataContratacao = new DateOnly(2015, 11, 11),
                            DataNascimento = new DateOnly(1990, 11, 11),
                            DepartamentoId = 3,
                            Email = "joão.alves@easydemandas.com",
                            Endereco = "Rua das Flores, 110",
                            Nome = "João",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Alves",
                            Telefone = "11900000010"
                        },
                        new
                        {
                            Id = 11,
                            CargoId = 1,
                            Cpf = "00000000011",
                            DataContratacao = new DateOnly(2016, 12, 12),
                            DataNascimento = new DateOnly(1991, 12, 12),
                            DepartamentoId = 4,
                            Email = "julia.almeida@easydemandas.com",
                            Endereco = "Rua das Flores, 111",
                            Nome = "Julia",
                            Perfil = "Suporte",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Almeida",
                            Telefone = "11900000011"
                        },
                        new
                        {
                            Id = 12,
                            CargoId = 2,
                            Cpf = "00000000012",
                            DataContratacao = new DateOnly(2017, 1, 13),
                            DataNascimento = new DateOnly(1992, 1, 13),
                            DepartamentoId = 5,
                            Email = "lucas.silva@easydemandas.com",
                            Endereco = "Rua das Flores, 112",
                            Nome = "Lucas",
                            Perfil = "Usuario",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Silva",
                            Telefone = "11900000012"
                        },
                        new
                        {
                            Id = 13,
                            CargoId = 3,
                            Cpf = "00000000013",
                            DataContratacao = new DateOnly(2018, 2, 14),
                            DataNascimento = new DateOnly(1993, 2, 14),
                            DepartamentoId = 6,
                            Email = "mariana.barbosa@easydemandas.com",
                            Endereco = "Rua das Flores, 113",
                            Nome = "Mariana",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Barbosa",
                            Telefone = "11900000013"
                        },
                        new
                        {
                            Id = 14,
                            CargoId = 4,
                            Cpf = "00000000014",
                            DataContratacao = new DateOnly(2019, 3, 15),
                            DataNascimento = new DateOnly(1994, 3, 15),
                            DepartamentoId = 7,
                            Email = "nicolas.soares@easydemandas.com",
                            Endereco = "Rua das Flores, 114",
                            Nome = "Nicolas",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Soares",
                            Telefone = "11900000014"
                        },
                        new
                        {
                            Id = 15,
                            CargoId = 5,
                            Cpf = "00000000015",
                            DataContratacao = new DateOnly(2020, 4, 16),
                            DataNascimento = new DateOnly(1995, 4, 16),
                            DepartamentoId = 1,
                            Email = "olivia.carvalho@easydemandas.com",
                            Endereco = "Rua das Flores, 115",
                            Nome = "Olivia",
                            Perfil = "Suporte",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Carvalho",
                            Telefone = "11900000015"
                        },
                        new
                        {
                            Id = 16,
                            CargoId = 1,
                            Cpf = "00000000016",
                            DataContratacao = new DateOnly(2021, 5, 17),
                            DataNascimento = new DateOnly(1996, 5, 17),
                            DepartamentoId = 2,
                            Email = "pedro.vieira@easydemandas.com",
                            Endereco = "Rua das Flores, 116",
                            Nome = "Pedro",
                            Perfil = "Usuario",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Vieira",
                            Telefone = "11900000016"
                        },
                        new
                        {
                            Id = 17,
                            CargoId = 2,
                            Cpf = "00000000017",
                            DataContratacao = new DateOnly(2022, 6, 18),
                            DataNascimento = new DateOnly(1997, 6, 18),
                            DepartamentoId = 3,
                            Email = "sara.ribeiro@easydemandas.com",
                            Endereco = "Rua das Flores, 117",
                            Nome = "Sara",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Ribeiro",
                            Telefone = "11900000017"
                        },
                        new
                        {
                            Id = 18,
                            CargoId = 3,
                            Cpf = "00000000018",
                            DataContratacao = new DateOnly(2023, 7, 19),
                            DataNascimento = new DateOnly(1998, 7, 19),
                            DepartamentoId = 4,
                            Email = "tiago.gomes@easydemandas.com",
                            Endereco = "Rua das Flores, 118",
                            Nome = "Tiago",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Gomes",
                            Telefone = "11900000018"
                        },
                        new
                        {
                            Id = 19,
                            CargoId = 4,
                            Cpf = "00000000019",
                            DataContratacao = new DateOnly(2024, 8, 20),
                            DataNascimento = new DateOnly(1999, 8, 20),
                            DepartamentoId = 5,
                            Email = "ursula.fernandes@easydemandas.com",
                            Endereco = "Rua das Flores, 119",
                            Nome = "Ursula",
                            Perfil = "Suporte",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Fernandes",
                            Telefone = "11900000019"
                        },
                        new
                        {
                            Id = 20,
                            CargoId = 5,
                            Cpf = "00000000020",
                            DataContratacao = new DateOnly(2015, 9, 21),
                            DataNascimento = new DateOnly(1980, 9, 21),
                            DepartamentoId = 6,
                            Email = "vitor.lopes@easydemandas.com",
                            Endereco = "Rua das Flores, 120",
                            Nome = "Vitor",
                            Perfil = "Usuario",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Lopes",
                            Telefone = "11900000020"
                        },
                        new
                        {
                            Id = 21,
                            CargoId = 1,
                            Cpf = "00000000021",
                            DataContratacao = new DateOnly(2016, 10, 22),
                            DataNascimento = new DateOnly(1981, 10, 22),
                            DepartamentoId = 7,
                            Email = "zeca.nascimento@easydemandas.com",
                            Endereco = "Rua das Flores, 121",
                            Nome = "Zeca",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Nascimento",
                            Telefone = "11900000021"
                        },
                        new
                        {
                            Id = 22,
                            CargoId = 2,
                            Cpf = "00000000022",
                            DataContratacao = new DateOnly(2017, 11, 23),
                            DataNascimento = new DateOnly(1982, 11, 23),
                            DepartamentoId = 1,
                            Email = "fernanda.cardoso@easydemandas.com",
                            Endereco = "Rua das Flores, 122",
                            Nome = "Fernanda",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Cardoso",
                            Telefone = "11900000022"
                        },
                        new
                        {
                            Id = 23,
                            CargoId = 3,
                            Cpf = "00000000023",
                            DataContratacao = new DateOnly(2018, 12, 24),
                            DataNascimento = new DateOnly(1983, 12, 24),
                            DepartamentoId = 2,
                            Email = "gabriel.teixeira@easydemandas.com",
                            Endereco = "Rua das Flores, 123",
                            Nome = "Gabriel",
                            Perfil = "Suporte",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Teixeira",
                            Telefone = "11900000023"
                        },
                        new
                        {
                            Id = 24,
                            CargoId = 4,
                            Cpf = "00000000024",
                            DataContratacao = new DateOnly(2019, 1, 25),
                            DataNascimento = new DateOnly(1984, 1, 25),
                            DepartamentoId = 3,
                            Email = "igor.araujo@easydemandas.com",
                            Endereco = "Rua das Flores, 124",
                            Nome = "Igor",
                            Perfil = "Usuario",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Araujo",
                            Telefone = "11900000024"
                        },
                        new
                        {
                            Id = 25,
                            CargoId = 5,
                            Cpf = "00000000025",
                            DataContratacao = new DateOnly(2020, 2, 26),
                            DataNascimento = new DateOnly(1985, 2, 26),
                            DepartamentoId = 4,
                            Email = "diana.melo@easydemandas.com",
                            Endereco = "Rua das Flores, 125",
                            Nome = "Diana",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Melo",
                            Telefone = "11900000025"
                        },
                        new
                        {
                            Id = 26,
                            CargoId = 1,
                            Cpf = "00000000026",
                            DataContratacao = new DateOnly(2021, 3, 27),
                            DataNascimento = new DateOnly(1986, 3, 27),
                            DepartamentoId = 5,
                            Email = "eduardo.rocha@easydemandas.com",
                            Endereco = "Rua das Flores, 126",
                            Nome = "Eduardo",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Rocha",
                            Telefone = "11900000026"
                        },
                        new
                        {
                            Id = 27,
                            CargoId = 2,
                            Cpf = "00000000027",
                            DataContratacao = new DateOnly(2022, 4, 28),
                            DataNascimento = new DateOnly(1987, 4, 28),
                            DepartamentoId = 6,
                            Email = "quintino.pinto@easydemandas.com",
                            Endereco = "Rua das Flores, 127",
                            Nome = "Quintino",
                            Perfil = "Suporte",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Pinto",
                            Telefone = "11900000027"
                        },
                        new
                        {
                            Id = 28,
                            CargoId = 3,
                            Cpf = "00000000028",
                            DataContratacao = new DateOnly(2023, 5, 1),
                            DataNascimento = new DateOnly(1988, 5, 1),
                            DepartamentoId = 7,
                            Email = "zélia.batista@easydemandas.com",
                            Endereco = "Rua das Flores, 128",
                            Nome = "Zélia",
                            Perfil = "Usuario",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Batista",
                            Telefone = "11900000028"
                        },
                        new
                        {
                            Id = 29,
                            CargoId = 4,
                            Cpf = "00000000029",
                            DataContratacao = new DateOnly(2024, 6, 2),
                            DataNascimento = new DateOnly(1989, 6, 2),
                            DepartamentoId = 1,
                            Email = "heitor.montes@easydemandas.com",
                            Endereco = "Rua das Flores, 129",
                            Nome = "Heitor",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Montes",
                            Telefone = "11900000029"
                        },
                        new
                        {
                            Id = 30,
                            CargoId = 5,
                            Cpf = "00000000030",
                            DataContratacao = new DateOnly(2015, 7, 3),
                            DataNascimento = new DateOnly(1990, 7, 3),
                            DepartamentoId = 2,
                            Email = "clarice.teves@easydemandas.com",
                            Endereco = "Rua das Flores, 130",
                            Nome = "Clarice",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Teves",
                            Telefone = "11900000030"
                        });
                });

            modelBuilder.Entity("easydemandasapi.Models.Chamado", b =>
                {
                    b.HasOne("easydemandasapi.Models.Empregado", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("easydemandasapi.Models.Departamento", b =>
                {
                    b.HasOne("easydemandasapi.Models.Empregado", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("easydemandasapi.Models.DetalhesChamado", b =>
                {
                    b.HasOne("easydemandasapi.Models.Chamado", "Chamado")
                        .WithOne("Detalhes")
                        .HasForeignKey("easydemandasapi.Models.DetalhesChamado", "ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("easydemandasapi.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chamado");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("easydemandasapi.Models.Empregado", b =>
                {
                    b.HasOne("easydemandasapi.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("easydemandasapi.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("easydemandasapi.Models.Chamado", b =>
                {
                    b.Navigation("Detalhes");
                });
#pragma warning restore 612, 618
        }
    }
}
