// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using easydemandasapi.Data;

#nullable disable

namespace easydemandasapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526012914_FixSeededPasswords")]
    partial class FixSeededPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("easydemandasapi.Models.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cargos");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            Nome = "CARGO INDETERMINADO"
                        });
                });

            modelBuilder.Entity("easydemandasapi.Models.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("easydemandasapi.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("integer");

                    b.Property<string>("Sigla")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            Nome = "DEPARTAMENTO INDETERMINADO",
                            ResponsavelId = 9999,
                            Sigla = "IND"
                        });
                });

            modelBuilder.Entity("easydemandasapi.Models.DetalhesChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Custo")
                        .HasColumnType("numeric");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Encaminhamentos")
                        .HasColumnType("text");

                    b.Property<string>("NivelCriticidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.ToTable("DetalhesChamados");
                });

            modelBuilder.Entity("easydemandasapi.Models.Empregado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CargoId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DataContratacao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Empregados");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            CargoId = 9999,
                            Cpf = "00000000000",
                            DataContratacao = new DateOnly(1900, 1, 1),
                            DataNascimento = new DateOnly(1900, 1, 1),
                            Email = "indeterminado@easydemandas.com",
                            Endereco = "Indeterminado",
                            Nome = "EMPREGADO",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "INDETERMINADO",
                            Telefone = "00000000000"
                        },
                        new
                        {
                            Id = 9001,
                            CargoId = 9999,
                            Cpf = "11111111111",
                            DataContratacao = new DateOnly(2020, 1, 1),
                            DataNascimento = new DateOnly(1985, 5, 10),
                            Email = "gestor@easydemandas.com",
                            Endereco = "Rua do Gestor, 123",
                            Nome = "Gestor",
                            Perfil = "Gestor",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Plataforma",
                            Telefone = "11999999999"
                        },
                        new
                        {
                            Id = 9002,
                            CargoId = 9999,
                            Cpf = "22222222222",
                            DataContratacao = new DateOnly(2021, 2, 1),
                            DataNascimento = new DateOnly(1990, 6, 15),
                            Email = "rh@easydemandas.com",
                            Endereco = "Rua do RH, 123",
                            Nome = "RH",
                            Perfil = "RH",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Usuario",
                            Telefone = "11888888888"
                        },
                        new
                        {
                            Id = 9003,
                            CargoId = 9999,
                            Cpf = "33333333333",
                            DataContratacao = new DateOnly(2022, 3, 1),
                            DataNascimento = new DateOnly(1992, 8, 20),
                            Email = "suporte@easydemandas.com",
                            Endereco = "Rua do Suporte, 123",
                            Nome = "Suporte",
                            Perfil = "Suporte",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Chamados",
                            Telefone = "11777777777"
                        },
                        new
                        {
                            Id = 9004,
                            CargoId = 9999,
                            Cpf = "44444444444",
                            DataContratacao = new DateOnly(2023, 4, 1),
                            DataNascimento = new DateOnly(1995, 10, 25),
                            Email = "usuario@easydemandas.com",
                            Endereco = "Rua do Usuario, 123",
                            Nome = "Usuario",
                            Perfil = "Usuario",
                            SenhaHash = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            Sobrenome = "Comum",
                            Telefone = "11666666666"
                        });
                });

            modelBuilder.Entity("easydemandasapi.Models.Chamado", b =>
                {
                    b.HasOne("easydemandasapi.Models.Empregado", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("easydemandasapi.Models.Departamento", b =>
                {
                    b.HasOne("easydemandasapi.Models.Empregado", "Responsavel")
                        .WithMany()
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("easydemandasapi.Models.DetalhesChamado", b =>
                {
                    b.HasOne("easydemandasapi.Models.Chamado", "Chamado")
                        .WithOne("Detalhes")
                        .HasForeignKey("easydemandasapi.Models.DetalhesChamado", "ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("easydemandasapi.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("easydemandasapi.Models.Empregado", b =>
                {
                    b.HasOne("easydemandasapi.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("easydemandasapi.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("easydemandasapi.Models.Chamado", b =>
                {
                    b.Navigation("Detalhes");
                });
#pragma warning restore 612, 618
        }
    }
}
